---
apiVersion: v1
kind: Namespace
metadata:
  name: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service-account
  namespace: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clientadmin-service-account
  namespace: prop-development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: partner-service-account
  namespace: prop-development
